baseURL = 'https://tobyqin.github.io/docs/'
languageCode = 'en-us'
title = "Toby's Docs"
theme = 'hextra'

# Enable search
[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "search"
isPlainText = true
notAlternative = true

# Menu configuration
[menu]
main = [
    { name = "Documentation", url = "/docs/", weight = 1 },
    { name = "Blog", url = "./posts/", weight = 2 },
    { name = "About", url = "/about/", weight = 3 },
    { name = "GitHub", url = "https://github.com/tobyqin", weight = 4 },
]

# Theme parameters
[params]
displayUpdatedDate = true
dateFormat = "January 2, 2006"
author = "Toby Qin"
description = "Documentation and notes by Toby Qin"

[params.social]
github = "tobyqin"

# Search configuration
[params.search]
enable = true